**Importing libraries**

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

**Importing dataset**

In [32]:
dataset = pd.read_csv('parkinsons_new.csv')

**Pre-Processing & EDA**

In [33]:
dataset.head()

name  age sex  MDVP:Fo(Hz)  ...  Shimmer:DDA      NHR     HNR  status
0  phon_R01_S01_1   50   M      119.992  ...      0.06545  0.02211  21.033       1
1  phon_R01_S01_2   52   F      122.400  ...      0.09403  0.01929  19.085       1
2  phon_R01_S01_3   54   M      116.682  ...      0.08270  0.01309  20.651       1
3  phon_R01_S01_4   57   F      116.676  ...      0.08771  0.01353  20.644       1
4  phon_R01_S01_5   59   M      116.014  ...      0.10470  0.01767  19.649       1

[5 rows x 20 columns]

In [34]:
dataset.tail()

name  age sex  MDVP:Fo(Hz)  ...  Shimmer:DDA      NHR     HNR  status
190  phon_R01_S50_2   74   F      174.188  ...      0.07008  0.02764  19.517       0
191  phon_R01_S50_3   52   F      209.516  ...      0.04812  0.01810  19.147       0
192  phon_R01_S50_4   62   F      174.688  ...      0.03804  0.10715  17.883       0
193  phon_R01_S50_5   78   F      198.764  ...      0.03794  0.07223  19.020       0
194  phon_R01_S50_6   69   F      214.289  ...      0.03078  0.04398  21.209       0

[5 rows x 20 columns]

In [35]:
dataset.shape

(195, 20)

In [36]:
dataset.columns

Index(['name', 'age', 'sex', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)',
       'MDVP:Jitter(%)', 'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ',
       'Jitter:DDP', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3',
       'Shimmer:APQ5', 'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status'],
      dtype='object')

In [37]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   age               195 non-null    int64  
 2   sex               195 non-null    object 
 3   MDVP:Fo(Hz)       195 non-null    float64
 4   MDVP:Fhi(Hz)      195 non-null    float64
 5   MDVP:Flo(Hz)      195 non-null    float64
 6   MDVP:Jitter(%)    195 non-null    float64
 7   MDVP:Jitter(Abs)  195 non-null    float64
 8   MDVP:RAP          195 non-null    float64
 9   MDVP:PPQ          195 non-null    float64
 10  Jitter:DDP        195 non-null    float64
 11  MDVP:Shimmer      195 non-null    float64
 12  MDVP:Shimmer(dB)  195 non-null    float64
 13  Shimmer:APQ3      195 non-null    float64
 14  Shimmer:APQ5      195 non-null    float64
 15  MDVP:APQ          195 non-null    float64
 16  Shimmer:DDA       195 non-null    float64
 1

In [38]:
dataset.describe()

age  MDVP:Fo(Hz)  ...         HNR      status
count  195.000000   195.000000  ...  195.000000  195.000000
mean    64.374359   154.228641  ...   21.885974    0.753846
std      9.095051    41.390065  ...    4.425764    0.431878
min     50.000000    88.333000  ...    8.441000    0.000000
25%     57.000000   117.572000  ...   19.198000    1.000000
50%     63.000000   148.790000  ...   22.085000    1.000000
75%     72.000000   182.769000  ...   25.075500    1.000000
max     79.000000   260.105000  ...   33.047000    1.000000

[8 rows x 18 columns]

In [39]:
pd.isnull(dataset).sum()

name                0
age                 0
sex                 0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
dtype: int64

In [40]:
#droping a particular column, axis =1
dataset = dataset.drop(['name'], axis=1)

In [41]:
dataset = pd.get_dummies(dataset, prefix_sep='sex')

In [42]:
dataset.head()

age  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...  status  sexsexF  sexsexM
0   50      119.992       157.302  ...       1        0        1
1   52      122.400       148.650  ...       1        1        0
2   54      116.682       131.111  ...       1        0        1
3   57      116.676       137.871  ...       1        1        0
4   59      116.014       141.781  ...       1        0        1

[5 rows x 20 columns]

In [43]:
X = dataset.loc[:, dataset.columns !="status"]
y = dataset["status"]

In [44]:
X.head()

age  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...     HNR  sexsexF  sexsexM
0   50      119.992       157.302  ...  21.033        0        1
1   52      122.400       148.650  ...  19.085        1        0
2   54      116.682       131.111  ...  20.651        0        1
3   57      116.676       137.871  ...  20.644        1        0
4   59      116.014       141.781  ...  19.649        0        1

[5 rows x 19 columns]

In [45]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

**Train-Test split**

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state =0)

In [47]:
print ("Dimention for X train:", X_train.shape)
print ("Dimention for X test:", X_test.shape)
print ("Dimention for y train:", y_train.shape)
print ("Dimention for y test:", y_test.shape)

Dimention for X train: (156, 19)
Dimention for X test: (39, 19)
Dimention for y train: (156,)
Dimention for y test: (39,)


**Standardization of Data**

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [49]:
X_train

array([[-1.10902309,  0.42106183,  0.05057195, ...,  0.92083391,
        -1.        ,  1.        ],
       [-0.67514823, -0.95694554, -0.73133513, ..., -0.65388412,
         1.        , -1.        ],
       [ 0.40953893,  1.21847901,  0.28739437, ..., -0.67914342,
        -1.        ,  1.        ],
       ...,
       [-0.24127336,  0.41390707,  2.52073344, ...,  0.87253104,
         1.        , -1.        ],
       [ 1.16881995,  2.46491405,  0.59348186, ...,  1.11958473,
         1.        , -1.        ],
       [ 0.73494508, -1.09278562, -0.91648442, ...,  1.06308366,
        -1.        ,  1.        ]])

In [50]:
X_test

array([[ 3.01070218e-01, -1.39240702e+00, -1.03177646e+00,
        -6.39882078e-01, -4.06992866e-01, -1.42903286e-01,
        -2.98448321e-01, -3.22593528e-01, -2.97492537e-01,
        -4.07764083e-01, -4.23973499e-01, -2.99011770e-01,
        -3.73880760e-01, -5.11323405e-01, -2.98999852e-01,
        -4.23039828e-01,  1.08991102e-01, -1.00000000e+00,
         1.00000000e+00],
       [-1.32804646e-01, -4.35375863e-01, -4.44074995e-01,
         4.09642413e-01, -6.72245888e-01, -6.83337529e-01,
        -6.97675522e-01, -6.78064904e-01, -6.96714983e-01,
        -8.99920345e-01, -8.62663742e-01, -8.87426410e-01,
        -8.78534519e-01, -7.43171542e-01, -8.87418927e-01,
        -4.91188069e-01,  8.75411485e-01, -1.00000000e+00,
         1.00000000e+00],
       [ 4.09538934e-01,  1.20494772e+00,  8.41732685e-02,
         1.99829396e+00, -8.87883237e-01, -9.80576363e-01,
        -7.75045135e-01, -8.33795221e-01, -7.76146840e-01,
        -1.05563369e+00, -9.94270816e-01, -1.06461407e+00,
    

**Classification SVM**

**Linear**

In [51]:
from sklearn import svm
cl = svm.SVC(kernel='linear', C=0.01)
cl.fit(X_train, y_train)

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [52]:
y_pred = cl.predict(X_train)

In [53]:
y_pred_1 = cl.predict(X_test)
y_pred_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Models Performance**

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred_1)
cm

array([[ 0, 10],
       [ 0, 29]])

In [55]:
acc = accuracy_score(y_test, y_pred_1)
acc

0.7435897435897436

In [56]:
cl.n_support_

array([38, 40], dtype=int32)

**Grid Search**

In [57]:
from sklearn.model_selection import GridSearchCV
parameters = {'C': [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000, 5000],
              'degree': [2, 3, 4, 5],
              'gamma':[0.001, 0.01, 0.1, 0.5, 1],
              'kernel': ['rbf','poly']
              }        
cl = svm.SVC()
grid = GridSearchCV(cl, parameters, cv=10)
grid.fit(X_train, y_train)
print(grid.best_params_)
print(grid.best_estimator_)

{'C': 5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}
SVC(C=5, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [58]:
from sklearn.metrics import classification_report
grid_prediction = grid.predict(X_test)
print(classification_report(y_test, grid_prediction))

              precision    recall  f1-score   support

           0       1.00      0.80      0.89        10
           1       0.94      1.00      0.97        29

    accuracy                           0.95        39
   macro avg       0.97      0.90      0.93        39
weighted avg       0.95      0.95      0.95        39

